name: AUTO
on: [push]

jobs:
  job-auto:
    runs-on: ubuntu-latest
    steps:
      - name: Automate push 
        run: |
          pwd
          ls -a 
          java --version
          git init

          #git remote add origin "git@github.com:hiteshh47/github-actions-h.git"
          #Above does not work because the VM at which this command will run
          #does not have SSH keys configured like you do with your local machine
          #hence you will need you use some kind of auth: GITHUB_TOKEN

          git remote add origin "https://hiteshh47:{{secrets.GITHUB_TOKEN}}@github.com/hiteshh47/github-actions-h.git"
          git fetch
          git checkout master 
          git branch --set-upstream-to=origin/master
          git pull 
          ls -a 
          echo $RANDOM >> random.txt
          git add .
          git commit -m " random number file"
          git push
