name: AUTO
on: [push]

jobs:
  job-auto:
    runs-on: ubuntu-latest
    steps:
      - name: Automate push 
        run: |
          pwd
          ls -a 
          java --version
          git init
          git remote add "https://github.com/hiteshh47/github-actions-h.git"