name: Container
on: [push]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container: 
      image: node:19-bullseye-slim 

    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
          type -a node

      - name: Step with container
        uses: docker://node:18-alpine3.16
        with:
          entrypoint: '/usr/local/bin/node'
          args: -v





