name: Container
on: [push]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container: 
      image: node:18-alpine3.16

    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
          
