name: Container
on: [push]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container: 
      image: node:18-alpine3.16

    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release

      - name: Step with container
        uses: docker://node:19-bullseye-slim 
        with:
          entrypoint: '/bin/echo'
          args: hello





