name: matrix
on: [pull_request]

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node_v: [5,8,10]
      fail-fast: true
    runs-on: ${{ matrix.os}}
    steps:
      - name: Log node version
        run: node --version
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_v}}
      - name: Log node version
        run: node --version
