name: Shell command

on: [push]

jobs:
  run-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "hello github"
      - name: multi commands
        run: |
          node -v
          npm -v